### ISSUE TITLE
Claiming acts like it's a page

### ISSUE THREAD

**Issue by dwertheimer** [Ilnicki010/support-local-businesses-app#12]
When I click "claim" it sends me to what looks like a page "http://localhost:3000/claim-business" but that URL doesn't actually work, and if I try to send that to someone, like the owner of the restaurant and they go there, it actually crashes the app. I would suggest we put the business ID behind it: http://localhost:3000/claim-business/12321414 and then have it actually work in the router so that someone could come directly to that link to register.

**Comment by dwertheimer** [comment]
Maybe leave the results in Context

**Comment by Ilnicki010** [comment]
Check out PR, I used route params to pass place_id then needed data (phone number, place name) is fetched from G places using provided id. I think this solves that problem
