### ISSUE TITLE
Add location check and automatically fill in the location field with your location

### ISSUE THREAD

**Issue by dwertheimer** [Ilnicki010/support-local-businesses-app#17]
The question is when to pop up the location request. Some options:
a) at page load -- seems intrusive
b) when user clicks on that field -- problematic because I made that field the default focus on page load. We could re-order the fields and put the filter first...maybe that's the best idea. 
c) maybe n seconds after page load so that you see the page and can start reading it, but then the location request pops up. This might be easiest/cleanest

Note: once location services gives you lat/long, we need to then convert that into a human-readable location name to populate the field value

What do you think @Ilnicki010 ?

**Comment by Ilnicki010** [comment]
Sorry for the slow response, but what do you think about the button "use your location" instead of pop up box?
https://developers.google.com/web/fundamentals/native-hardware/user-location/

**Comment by dwertheimer** [comment]
Yes, I agree. That's better.
